### Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

### Задание 3
Решите систему уравнений:

4x + 2y + z = 4 <br>
x + 3y = 12<br>
5y + 4z = -3

In [3]:
import numpy as np

In [4]:
# Задание 1
# https://stackoverflow.com/questions/15748001/reversed-array-in-numpy
# реверс в NumPy
a = np.array(range(10))
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [13]:
# создаем матрицу
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

In [8]:
# посмотреть ее диагональ
# если надо сдвинуть диагональ от центральной, то можно использовать параметр
# (offset=1) - на одну выше, или (offset=-1) - на одну ниже главной диагонали
matrix.diagonal()

array([1, 5, 9])

In [10]:
# два способа решения. Через метод trace (след матрицы) или через sum - сложение элементов
matrix.trace()

15

In [14]:
sum(matrix.diagonal())

15

### Задание 3
Решите систему уравнений:<br> 
4x + 2y + z = 4<br> 
x + 3y = 12<br>
5y + 4z = -3

In [16]:
# коэффициенты при переменных в левой части уравнения

a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )

In [17]:
# значения в правой части уравнения

b = np.array( [4, 12, -3] )

In [18]:
# решение

from numpy import linalg

In [20]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [21]:
# проверка верности

np.allclose( np.dot(a, linalg.solve(a, b)), b )

True